[[constraint]]
  name = "github.com/gin-gonic/autotls"
  version = "0.0.2"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/tyauvil/gin-commitment"
  install = [ "./..." ]
